---
version: '2'

run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true

output:
  sort-order:
    - linter
    - severity
    - file
  path-prefix: ''

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - gocritic
    - godot
    - gomoddirectives
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - assets
      - configs
      - doc
      - proto
      - scripts
      - tasks
      - web
      - third_party$
      - builtin$
      - examples$

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
    nakedret:
      max-func-lines: 1
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          xml: camel
          bson: snake
          avro: snake
          mapstructure: kebab

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
  fix: false

formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - assets
      - configs
      - doc
      - proto
      - scripts
      - tasks
      - web
      - third_party$
      - builtin$
      - examples$
